package models;
// Generated 13-ene-2017 13:34:48 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Etapa generated by hbm2java
 */
public class Etapa implements java.io.Serializable {

	private int numetapa;
	private Ciclista ciclista;
	private Integer kms;
	private String salida;
	private String llegada;
	private Set puertos = new HashSet(0);
	private Set llevas = new HashSet(0);

	public Etapa() {
	}

	public Etapa(int numetapa) {
		this.numetapa = numetapa;
	}

	public Etapa(int numetapa, Ciclista ciclista, Integer kms, String salida, String llegada, Set puertos, Set llevas) {
		this.numetapa = numetapa;
		this.ciclista = ciclista;
		this.kms = kms;
		this.salida = salida;
		this.llegada = llegada;
		this.puertos = puertos;
		this.llevas = llevas;
	}

	public int getNumetapa() {
		return this.numetapa;
	}

	public void setNumetapa(int numetapa) {
		this.numetapa = numetapa;
	}

	public Ciclista getCiclista() {
		return this.ciclista;
	}

	public void setCiclista(Ciclista ciclista) {
		this.ciclista = ciclista;
	}

	public Integer getKms() {
		return this.kms;
	}

	public void setKms(Integer kms) {
		this.kms = kms;
	}

	public String getSalida() {
		return this.salida;
	}

	public void setSalida(String salida) {
		this.salida = salida;
	}

	public String getLlegada() {
		return this.llegada;
	}

	public void setLlegada(String llegada) {
		this.llegada = llegada;
	}

	public Set getPuertos() {
		return this.puertos;
	}

	public void setPuertos(Set puertos) {
		this.puertos = puertos;
	}

	public Set getLlevas() {
		return this.llevas;
	}

	public void setLlevas(Set llevas) {
		this.llevas = llevas;
	}

}
